# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/NamKhanh/python-app/ui/future_forecase_item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(210, 45)
        self.lb_time = QtWidgets.QLabel(parent=Form)
        self.lb_time.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.lb_time.setObjectName("lb_time")
        self.lb_img = QtWidgets.QLabel(parent=Form)
        self.lb_img.setGeometry(QtCore.QRect(70, 0, 51, 41))
        self.lb_img.setText("")
        self.lb_img.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/NamKhanh/python-app/ui/../img/sun (1).png"))
        self.lb_img.setScaledContents(True)
        self.lb_img.setObjectName("lb_img")
        self.lb_description = QtWidgets.QLabel(parent=Form)
        self.lb_description.setGeometry(QtCore.QRect(130, 0, 81, 31))
        self.lb_description.setObjectName("lb_description")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_time.setText(_translate("Form", "22/11 5h"))
        self.lb_description.setText(_translate("Form", "Sunny"))
