# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/NamKhanh/python-app/ui/note_item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 150)
        Form.setStyleSheet("QWidget#Form {\n"
"    background-color: #202c3c;\n"
"    color: white;\n"
"    border: 1px solid #1e90ff;\n"
"    border-radius: 4px;\n"
"    margin: 0px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #1e90ff;\n"
"    color: white;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    border: none;\n"
"    min-width: 60px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1873cc;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #2c3e50;\n"
"    color: white;\n"
"    border: 1px solid #1e90ff;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QLabel {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.note = QtWidgets.QLabel(parent=Form)
        self.note.setObjectName("note")
        self.verticalLayout.addWidget(self.note)
        self.txt_note = QtWidgets.QTextEdit(parent=Form)
        self.txt_note.setMinimumSize(QtCore.QSize(0, 60))
        self.txt_note.setObjectName("txt_note")
        self.verticalLayout.addWidget(self.txt_note)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lb_time = QtWidgets.QLabel(parent=Form)
        self.lb_time.setText("")
        self.lb_time.setObjectName("lb_time")
        self.horizontalLayout.addWidget(self.lb_time)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_edit = QtWidgets.QPushButton(parent=Form)
        self.btn_edit.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout_2.addWidget(self.btn_edit)
        self.btn_delete = QtWidgets.QPushButton(parent=Form)
        self.btn_delete.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_2.addWidget(self.btn_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.note.setText(_translate("Form", "Note"))
        self.label.setText(_translate("Form", "Time"))
        self.btn_edit.setText(_translate("Form", "Edit"))
        self.btn_delete.setText(_translate("Form", "Delete"))
